path = ['C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN1_OA3_f10_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN1_OA3_f40_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN2_OA3_f40_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN2_OA3_f40_n30\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN3_OA3_f10_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN3_OA3_f30_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN4_OA3_f10_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN4_OA3_f10_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN5_OA3_f10_n30\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN5_OA3_f40_n30\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN6_OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN6_OA3_f30_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNA_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNA_OA3OA3_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNB_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNB_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNC_OA3OA3_f10_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNC_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCND_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCND_OA3OA3_f20_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNE_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNE_OA3OA3_f40_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNF_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNF_OA3OA3_f30_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNG_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNG_OA3OA3_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNH_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNH_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNI_OA3OA3_f10_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNI_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNJ_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNJ_OA3OA3_f20_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNK_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNK_OA3OA3_f40_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNL_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNL_OA3OA3_f30_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNM_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNM_OA3A2_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNN_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNN_OA3A2_f20_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNO_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNO_OA3A2_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNP_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNP_OA3A2_f20_n40\\Nifti']

trainPath = [
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN1_OA3_f10_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN1_OA3_f40_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN2_OA3_f40_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN2_OA3_f40_n30\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN3_OA3_f10_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN3_OA3_f30_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN4_OA3_f10_n10\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN4_OA3_f10_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN6_OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN6_OA3_f30_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNA_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNA_OA3OA3_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNB_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNB_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNC_OA3OA3_f10_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNC_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCND_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCND_OA3OA3_f20_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNE_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNE_OA3OA3_f40_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNF_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNF_OA3OA3_f30_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNG_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNG_OA3OA3_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNH_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNH_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNI_OA3OA3_f10_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNI_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNJ_OA3OA3_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNJ_OA3OA3_f20_n40\\Nifti'
       ]
testPath = [
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN5_OA3_f10_n30\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCN5_OA3_f40_n30\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNM_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNM_OA3A2_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNN_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNN_OA3A2_f20_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNO_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNO_OA3A2_f40_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNP_OA3A2_f20_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNP_OA3A2_f20_n40\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNK_OA3OA3_f20_n50\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNK_OA3OA3_f40_n50\\Nifti']

validPath = [
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNL_OA3OA3_f30_n20\\Nifti',
       'C:\\Users\\shiyx\\Documents\\Data\\SYN\\FCNL_OA3OA3_f30_n40\\Nifti']
#
# path_n1030 = []
# for i in path:
#     if 'n10'in i or 'n20'in i or 'n30'in i:
#         path_n1030.append(i)